"""initial orders migrate

Revision ID: 3c7457de4f26
Revises: 
Create Date: 2026-01-13 18:10:17.185097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7457de4f26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('outbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=100), nullable=False),
    sa.Column('routing_key', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_outbox_messages_created_at'), 'outbox_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_event_type'), 'outbox_messages', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_messages_published'), 'outbox_messages', ['published'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_index(op.f('ix_outbox_messages_published'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_event_type'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_created_at'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_table('orders')
    # ### end Alembic commands ###
